Repository ironcore-dev/ironcore-csi-driver, pull requests merged in 2023-03, with the labels that each got.

#206 Improve response struct creation
  .github/release-drafter.yml
  config/samples/storage-class.yaml
  pkg/driver/controller.go
  pkg/driver/node.go
Labels: enhancement, size/L

#205 Honor `AccessibleTopology` during `Volume` creation
  pkg/driver/controller.go
  pkg/driver/driver_test.go
Labels: bug, size/L

#208 Use distroless image in docker build
  Dockerfile
  hack/print-missing-deps.sh
Labels: enhancement, ok-to-image, size/L

#210 Call `ControllerUnpublishVolume` if a `Node` is gone
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/driver_test.go
Labels: size/S

#218 Remove node IP, driver name and version from config
  cmd/main.go
  cmd/options/options.go
  pkg/driver/driver.go
  pkg/driver/identity.go
  pkg/driver/identity_test.go
  pkg/driver/suite_test.go
Labels: enhancement, size/M

#219 Fix config initialisation
  cmd/main.go
Labels: bug, size/S

#220 Fix node controller config init
  cmd/main.go
  pkg/driver/driver.go
Labels: bug, size/XS

#223 Improve logging in controller and node driver
  pkg/driver/controller.go
Labels: size/XS, chore

#225 Remove `resizer` and `snapshotter` sidecars from controller and node driver
  config/manager/controller.yaml
  config/manager/node.yaml
Labels: size/M

#233 Add `Node` driver suite tests
  Makefile
  go.mod
  go.sum
  hack/update-gomock
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/identity_test.go
  pkg/driver/mocks/mountutils.go
  pkg/driver/mocks/osutils.go
  pkg/driver/mountutils/mountutils.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/driver/osutils/osutils.go
  pkg/driver/suite_test.go
Labels: enhancement, size/XXL

#235 Add cache cleaning GH workflow
  .github/workflows/clean-cache.yaml
Labels: size/M, chore

#237 Refactor `Node` driver tests
  .github/workflows/clean.yml
  Makefile
  hack/check.sh
  hack/fix-mountwrapper-mock.sh
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/driver.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/utils/mount/mock_mountutils_unix.go
  pkg/utils/mount/mountutils_unix.go
  pkg/utils/os/mock_osutils_unix.go
  pkg/utils/os/osutils_unix.go
  pkg/utils/util.go
Labels: enhancement, size/L

#244 Announce proper driver version
  pkg/driver/driver.go
  pkg/driver/identity.go
  pkg/driver/identity_test.go
  pkg/driver/version.go
Labels: enhancement, size/M
