Repository ironcore-dev/ironcore-csi-driver, pull requests merged in 2023-11, with the labels that each got.

#365 Implement `ControllerModifyVolume` in driver controller
  go.mod
  go.sum
  pkg/driver/controller.go
  pkg/driver/controller_test.go
Labels: enhancement, size/S

#380 Add `golangci-lint` installation to `Makefile`
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  pkg/driver/node_test.go
Labels: enhancement, size/S

#381 Project rename to ` ironcore-csi-driver`
  .github/dependabot.yml
  .github/workflows/publish-docker.yml
  .gitignore
  CODEOWNERS
  CODE_OF_CONDUCT.md
  Dockerfile
  Makefile
  README.md
  cmd/main.go
  cmd/options/options.go
  config/default/controller_setenv_replicas.yaml
  config/default/kustomization.yaml
  config/default/node_setenv.yaml
  config/manager/controller.yaml
  config/manager/csidriver.yaml
  config/manager/node.yaml
  config/samples/kube_secret_template.yaml
  config/samples/onmetal-machine.yaml
  config/samples/onmetal-volume.yaml
  config/samples/pod.yaml
  config/samples/pvc.yaml
  config/samples/storage-class.yaml
  docs/deployment/deploy_manually.md
  docs/development/setup.md
  docs/troubleshooting/troubleshooting.md
  docs/usage/basic.md
  go.mod
  go.sum
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/identity_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/driver/suite_test.go
Labels: documentation, enhancement, ok-to-image, size/XL, breaking

#383 Make project REUSE compliant
  .golangci.yaml
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  Makefile
  README.md
  cmd/main.go
  cmd/options/options.go
  hack/license-header.txt
  pkg/driver/constants.go
  pkg/driver/controller.go
  pkg/driver/controller_test.go
  pkg/driver/driver.go
  pkg/driver/identity.go
  pkg/driver/identity_test.go
  pkg/driver/node.go
  pkg/driver/node_test.go
  pkg/driver/suite_test.go
  pkg/driver/version.go
  pkg/utils/mount/mock_mountutils_unix.go
  pkg/utils/mount/mount.go
  pkg/utils/mount/mountutils_unix.go
  pkg/utils/os/mock_osutils_unix.go
  pkg/utils/os/osutils_unix.go
  pkg/utils/util.go
Labels: documentation, enhancement, ok-to-image, size/L
