Repository ironcore-dev/ironcore-csi-driver, pull requests merged in 2023-12, with the labels that each got.

#385 Remove duplicate Table of Contents entry in README
  README.md
Labels: documentation, size/XS

#390 Switch from `pull_request_target` to `pull_request` trigger
  .github/workflows/release-drafter.yml
  .github/workflows/size-label.yml
  CODEOWNERS
Labels: size/S, ok-to-image, chore

#391 Bump `envtest` k8s version to 1.28
  Makefile
Labels: size/XS, ok-to-image, chore
