Repository ironcore-dev/ironcore-csi-driver, pull requests merged in 2024-04, with the labels that each got.

#455 Node driver should not fail if a volume is already mounted
  pkg/driver/node.go
  pkg/driver/node_test.go
Labels: bug, size/XS

#467 Bump golang to 1.22.2 and `k8s.io/*` to 0.29.4
  .github/dependabot.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/release-drafter.yml
  .github/workflows/size-label.yml
  Makefile
  go.mod
  go.sum
Labels: size/S, chore

#469 Ignore `k8s.io/mount-utils` in dependabot configuration
  .github/dependabot.yml
Labels: size/XS, chore
