Repository ironcore-dev/ironcore-csi-driver, pull requests merged in 2025-09, with the labels that each got.

#610 Bump golangci-lint to v2.4
  .github/workflows/lint.yml
  Makefile
Labels: size/XS, chore

#611 Refactor Makefile
  Makefile
Labels: size/M, chore, area/iaas, area/storage

#618 Group dependabot updates
  .github/dependabot.yml
Labels: size/S, chore
